# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Trigger on push to master branch
trigger:
- master

# Trigger on pull request to master branch
pr:
- master

jobs:
- job:
  displayName: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:  
      GCC-7 Debug:
        CC: gcc-7
        CXX: g++-7
        BuildType: Debug

      GCC-7 Release:
        CC: gcc-7
        CXX: g++-7
        BuildType: Release

      GCC-8 Debug:
        CC: gcc-8
        CXX: g++-8
        BuildType: Debug

      GCC-8 Release:
        CC: gcc-8
        CXX: g++-8
        BuildType: Release
        
      GCC-9 Debug:
        CC: gcc-9
        CXX: g++-9
        BuildType: Debug

      GCC-9 Release:
        CC: gcc-9
        CXX: g++-9
        BuildType: Release

      Clang-8 Debug:
        CC: clang-8
        CXX: clang++-8
        BuildType: Debug

      Clang-8 Release:
        CC: clang-8
        CXX: clang++-8
        BuildType: Release        

  steps:
  - checkout: self
    submodules: true
  
  - script: |
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      sudo apt-get update
      sudo apt-get install -y gcc-7 g++-7 gcc-8 g++-8 gcc-9 g++-9
      sudo update-alternatives --install /usr/bin/cc cc /usr/bin/$(CC) 100
      sudo update-alternatives --set cc /usr/bin/$(CC)
      sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/$(CXX) 100
      sudo update-alternatives --set c++ /usr/bin/$(CXX)
      if [[ "$CXX" == clang++* ]]; then sudo apt-get install -y libomp-dev ; fi
    displayName: 'Install Build Dependencies'

  - task: CMake@1
    displayName: 'CMake .. -DCMAKE_BUILD_TYPE=$(BuildType)'
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '.. -DCMAKE_BUILD_TYPE=$(BuildType)'

  - script: make -j -C build
    displayName: 'Compiling'
